---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies:
  "jm1.ansible": '>=2022.10.23'
  "jm1.pkg": '>=2022.12.10'
  "openstack.cloud": '>=1.9.1,<2.0.0'
description: null
documentation: https://github.com/jm1/ansible-collection-jm1-openstack/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-jm1-openstack
issues: https://github.com/jm1/ansible-collection-jm1-openstack/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: openstack
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-jm1-openstack
tags: null
version: 2022.12.20
