---
# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

- name: Satisfy requirements for collection jm1.openstack on Debian 10 (Buster)
  when: distribution_id == ['Debian', '10']
  jm1.pkg.meta_pkg:
    name: "jm1-openstack-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - python-backports.tempfile
    - python-openstacksdk
    - python3-openstacksdk

- name: Satisfy requirements for collection jm1.openstack on Ubuntu 20.04 LTS (Focal Fossa)
  when: distribution_id == ['Ubuntu', '20.04']
  jm1.pkg.meta_pkg:
    name: "jm1-openstack-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - python3-openstacksdk
