---
# Copyright (c) 2022-2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Enable yum repositories for OpenStack
  ansible.builtin.package:
    name: centos-release-openstack-wallaby

- name: Install package dependencies for Red Hat Enterprise Linux 8 and CentOS 8
  jm1.pkg.meta_pkg:
    name: "jm1-openstack-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - centos-release-openstack-wallaby
    - python3-openstacksdk
