---
# NOTE: Synchronize changes with README.md

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

# No need to update apt cache here because role jm1.pkg.setup handles apt cache updates already

- name: Install package dependencies
  jm1.pkg.meta_pkg:
    name: "jm1-openstack-setup"
    version: "2"
    depends:
    - jm1-pkg-setup
    - python3-openstacksdk
