---
# Copyright (c) 2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Satisfy requirements for collection jm1.openstack on Red Hat Enterprise Linux 7 and CentOS 7
  when: distribution_id | last == '7'
  block:
  - name: Enable yum repositories for OpenStack
    ansible.builtin.package:
      name: centos-release-openstack-train

  - name: Install package dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    jm1.pkg.meta_pkg:
      name: "jm1-openstack-setup"
      version: "1"
      depends:
      - jm1-pkg-setup
      - centos-release-openstack-train
      - python2-openstacksdk

  - name: Install pip dependencies for Red Hat Enterprise Linux 7 and CentOS 7
    ansible.builtin.pip:
      name: backports.tempfile

- name: Satisfy requirements for collection jm1.openstack on Red Hat Enterprise Linux 8 and CentOS 8
  when: distribution_id | last == '8'
  block:
  - name: Enable yum repositories for OpenStack
    ansible.builtin.package:
      name: centos-release-openstack-wallaby

  - name: Install package dependencies for Red Hat Enterprise Linux 8 and CentOS 8
    jm1.pkg.meta_pkg:
      name: "jm1-openstack-setup"
      version: "1"
      depends:
      - jm1-pkg-setup
      - centos-release-openstack-wallaby
      - python3-openstacksdk

- name: Satisfy requirements for collection jm1.openstack on Red Hat Enterprise Linux 9 and CentOS 9
  when: distribution_id | last == '9'
  block:
  - name: Enable yum repositories for OpenStack
    ansible.builtin.package:
      name: centos-release-openstack-zed

  - name: Install package dependencies for Red Hat Enterprise Linux 9 and CentOS 9
    jm1.pkg.meta_pkg:
      name: "jm1-openstack-setup"
      version: "1"
      depends:
      - jm1-pkg-setup
      - centos-release-openstack-zed
      - python3-openstacksdk
