---
# Copyright (c) 2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install package dependencies for Fedora
  jm1.pkg.meta_pkg:
    name: "jm1-openstack-setup"
    version: "1"
    depends:
    - jm1-pkg-setup
    - python3-openstacksdk
